-- Seed curated outbound GTM knowledge articles for Revomnis.
-- Safe to re-run: uses upsert on slug.

insert into public.knowledge_articles (
  slug,
  title,
  source_name,
  source_url,
  author_name,
  published_at,
  excerpt,
  body_md,
  revomnis_comment,
  topics,
  status,
  seo_title,
  seo_description
) values
(
  'fit-before-volume-in-outbound',
  'Why outbound fails when volume outruns fit',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-06-02T10:00:00Z',
  'Outbound breaks when teams scale sends before they define who is actually worth a conversation.',
  null,
  'Fit before volume is not a slogan for us — it is the operating rule. We classify accounts and contacts before sequencing so campaigns protect reply quality and meeting standards instead of optimizing for send volume.',
  array['ICP', 'targeting'],
  'published',
  'Fit before volume in outbound — Revomnis Knowledge',
  'Why outbound fails when volume outruns fit, and how Revomnis builds audience logic before campaigns scale.'
),
(
  'coordinated-email-and-linkedin',
  'Email and LinkedIn only work as one motion',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-06-09T10:00:00Z',
  'Treating cold email and LinkedIn as separate services creates mixed signals and weak handoffs.',
  null,
  'Revomnis runs email and LinkedIn against one ICP, one messaging system, and one meeting objective. LinkedIn reinforces familiarity; email carries scalable sequencing and reply generation. Separate vendors usually cannot hold that coherence.',
  array['LinkedIn', 'email', 'sequencing'],
  'published',
  'Coordinated email and LinkedIn outbound — Revomnis Knowledge',
  'How Revomnis coordinates email and LinkedIn as one outbound motion instead of two disconnected channels.'
),
(
  'protect-the-primary-domain',
  'Do not burn your primary domain on cold email',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-06-16T10:00:00Z',
  'Primary domains should not be the default sending layer for cold outbound.',
  null,
  'We operate client-branded secondary domains and managed inbox infrastructure so outbound can run with deliverability discipline while the primary brand domain stays protected. Infrastructure is part of the service, not a bolt-on.',
  array['deliverability', 'infrastructure'],
  'published',
  'Protect your primary domain in cold email — Revomnis Knowledge',
  'Why Revomnis uses managed secondary domains for cold email instead of risking the primary brand domain.'
),
(
  'qualified-meetings-not-calendar-spam',
  'A booked meeting is not automatically a qualified meeting',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-06-23T10:00:00Z',
  'Calendar volume without buyer-fit criteria creates noise for sales and weak pipeline quality.',
  null,
  'Before campaigns launch, we define fit signals, disqualifiers, and commercial intent criteria with the client. Reply handling and qualification sit inside the operating system so meetings handed over are worth the conversation.',
  array['qualification', 'meetings'],
  'published',
  'Qualified outbound meetings — Revomnis Knowledge',
  'How Revomnis defines and protects meeting quality instead of optimizing for raw booked-call volume.'
),
(
  'visible-not-black-box-outbound',
  'Outbound should be visible, not a black box',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-06-30T10:00:00Z',
  'Clients should see what is running, what is moving, and what is being learned — not just a monthly activity dump.',
  null,
  'The Revomnis portal is a visibility layer for managed outbound: campaign movement, meetings, segments, and insights. The product is still the operating system; the portal exists so clients are not buying a black box.',
  array['visibility', 'portal'],
  'published',
  'Visible outbound, not a black box — Revomnis Knowledge',
  'Why Revomnis pairs managed outbound with portal visibility instead of black-box reporting.'
),
(
  'messaging-tests-need-segment-logic',
  'Messaging tests are useless without segment logic',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-07-07T10:00:00Z',
  'A/B copy tests on a mixed audience produce noise, not learning.',
  null,
  'We test angles inside clear segments so persona learning and objection patterns are attributable. Insights are only useful when audience definition and campaign execution share the same logic.',
  array['messaging', 'ICP', 'testing'],
  'published',
  'Outbound messaging tests and segment logic — Revomnis Knowledge',
  'Why Revomnis ties messaging tests to segment logic so outbound learning is attributable.'
),
(
  'reply-handling-is-the-system',
  'Reply handling is not an afterthought',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-07-14T10:00:00Z',
  'Most outbound programs break after the first positive reply because nobody owns interpretation and next step.',
  null,
  'Revomnis monitors, interprets, and qualifies replies as part of the managed service. The path from reply to meeting is designed, not forwarded as an unstructured inbox dump.',
  array['replies', 'qualification'],
  'published',
  'Outbound reply handling — Revomnis Knowledge',
  'How Revomnis treats reply handling as part of the outbound operating system, not a handoff afterthought.'
),
(
  'anti-patterns-vanity-metrics',
  'Vanity metrics hide weak outbound systems',
  'Revomnis',
  'https://revomnis.com/',
  'Revomnis',
  '2026-07-21T10:00:00Z',
  'Open rates, connection counts, and raw meetings can look healthy while pipeline quality is poor.',
  null,
  'We refuse to sell vanity as proof. The metrics that matter are fit, conversation quality, qualified meetings, and what the market is teaching the system. If a report cannot explain movement and learning, it is theater.',
  array['anti-patterns', 'visibility'],
  'published',
  'Outbound vanity metrics to avoid — Revomnis Knowledge',
  'Which outbound vanity metrics Revomnis rejects, and what visibility should show instead.'
)
on conflict (slug) do update set
  title = excluded.title,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  author_name = excluded.author_name,
  published_at = excluded.published_at,
  excerpt = excluded.excerpt,
  body_md = excluded.body_md,
  revomnis_comment = excluded.revomnis_comment,
  topics = excluded.topics,
  status = excluded.status,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  updated_at = now();
